ENTRY(start)

SECTIONS
{
    . = ALIGN(8);

    .entry              : { KEEP(*(.multiboot_header)) __entry_start = .;      *(.entry)   }
    .text               : { __text_start = .;       *(.text)   }
    .data               : { __data_start = .;       *(.data)    }
    .rodata             : { __rodata_start = .;     *(.rodata)  }
    .bss                : { __bss_start = .;        *(.bss)     }
    
    __end = .;
}